shallow_clone: true

platform:
  - x64
# - x86

configuration:
  - Release
# - Debug

image:
  - Visual Studio 2015
# - Visual Studio 2017

environment:
  matrix:
    - MINICONDA: C:\Miniconda36-x64

init:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda install -y cmake h5py pytest
  - pip install pybind11

build_script:
  - if exist build.appveyor rmdir /Q /S build.appveyor
  - mkdir build.appveyor
  - cd build.appveyor && cmake -G "Visual Studio 14 2015 Win64" ..
  - cd build.appveyor && cmake --build . --target tests --config "%CONFIGURATION%"
  - cd python && python setup.py install

test_script:
  - "build.appveyor\\%CONFIGURATION%\\tests.exe --gtest_color=yes"
  - cd python/test && if exist "__pycache__" rmdir /Q /S "__pycache__"
  - cd python/test && pytest --color=yes
