branches:
  only:
    - master

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false

platform: x64
configuration: Release
image: Visual Studio 2017
cache:
  - c:\Tools\vcpkg\installed
  - c:\Users\appveyor\.julia

environment:
  matrix:
    - lang: Python3.7
    - lang: C++
    - lang: Julia 1.3
    - lang: Rust

for:
  -
    matrix:
      only:
        - lang: C++
    build:
      parallel: true
      verbosity: detailed
    only_commits:
      files:
        - .appveyor.yml
        - CMakeLists.txt
        - cxx/
        - deps/graphidx/
        - deps/doctest/
    build_script:
      - echo %APPVEYOR_BUILD_FOLDER%
      - vcpkg install hdf5 bzip2
      - git submodule update --recursive --init deps/graphidx
      - mkdir build.appveyor && cd build.appveyor && cmake .. -A x64 -DPYTHON_EXECUTABLE:FILEPATH=C:\Python37-x64\python.exe -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      - cmake --build . --target doctests --config "%CONFIGURATION%"
      - cmake --build . --config "%CONFIGURATION%"
    test_script: "%CONFIGURATION%\\doctests.exe -s"

  -
    matrix:
      only:
        - lang: Python3.7
    only_commits:
      files:
        - .appveyor.yml
        - cxx/
        - python/
        - deps/graphidx/
    build_script:
      - SET PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
      - python --version
      - git submodule update --recursive --init deps/graphidx
      -  pip3 install --only-binary all
            -r python/requirements.txt
            -r python/test/requirements.txt
      - cd python && python setup.py install
    test_script: pytest test

  -
    matrix:
      only:
        - lang: Julia 1.3
    only_commits:
      files:
        - .appveyor.yml
        - julia/
        - docs/src/julia/
    environment:
      julia_version: 1.3
      hub: "https://raw.githubusercontent.com/JuliaCI/Appveyor.jl"
      url: "version-1/bin/install.ps1"
    install:
      - ps: iex ((new-object net.webclient).DownloadString("$env:hub/$env:url"))
      - SET PATH=C:\julia\bin;%PATH%
      - julia --version
      - git submodule update --init deps/graphidx
    build_script:
      - ps: ci/setup_julia.ps1
    test_script:
      - julia --proj=julia -e "import Pkg; Pkg.test()"

  -
    matrix:
      only:
        - lang: Rust
    only_commits:
      files:
        - .appveyor.yml
        - Cargo.toml
        - rust/
    environment:
      target: x86_64-pc-windows-msvc
      channel: stable
    install:
      - curl -sSf -o rustup-init.exe https://win.rustup.rs
      - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
      - set PATH=%HOMEPATH%\.cargo\bin;%PATH%
      - rustc -Vv
      - cargo -V
      - git submodule update --init deps/graphidx
    build_script:
      - cargo build --verbose
    test_script:
      - cargo test
