language: cpp
dist: xenial

git:
  submodules: false

branches:
  only:
    - master

# https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
#addons:
  # apt:
  #   sources:
  #     - ubuntu-toolchain-r-test
  #   packages:
  #     - g++-7
  ## don't need a specific compiler for macos
  # homebrew:
  #   packages:
  #     - gcc    ## https://formulae.brew.sh/formula/gcc

env:
  - miniconda_base_url="https://repo.continuum.io/miniconda/Miniconda3-latest"

matrix:
  include:
    - os: linux
      env:
        - miniconda_url="$miniconda_base_url-Linux-x86_64.sh"
    - os: osx
      env:
        - miniconda_url="$miniconda_base_url-MacOSX-x86_64.sh"

cache:
  directories:
    - "$TRAVIS_BUILD_DIR/miniconda3"

before_cache:
  - pip uninstall -y treelas
  - rm -fr $TRAVIS_BUILD_DIR/miniconda3/envs
  - rm -fr $TRAVIS_BUILD_DIR/miniconda3/lib/python*/site-packages/treelas*


install:
  - git describe --tags
  - uname -a && echo $TRAVIS_OS_NAME && pwd
  - export CC=${C_COMPILER:-cc} && echo $CC && $CC --version
  - export CXX=${CXX_COMPILER:-c++} && echo $CXX && $CXX --version
  - echo | ${CC} -dM -E -x c -
  - if [[ ! -d $PWD/miniconda3/bin ]]; then
      wget $miniconda_url -O miniconda.sh;
      rm -fr miniconda3;
      bash miniconda.sh -b -p $PWD/miniconda3;
    fi
  - export PATH=$PWD/miniconda3/bin:$PATH;
  - conda install -y pytest networkx h5py numba cmake
  - pip install pybind11
  - python -m pybind11 --include
  - python -c 'from sys import byteorder as b; print("byte-order:", b)'

script:
  - mkdir -p build && cd build
  - CXX=$CXX CC=$CC cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make && ./tests
  - cd ../python && pwd && rm -fr build
  - CC=$CXX python setup.py install
  - py.test --color=yes test

notifications:
  email:
    on_failure: change
    on_success: change
