language: cpp

git:
  submodules: false

sudo: false

## https://docs.travis-ci.com/user/caching/
# cache:
#   directories:
#     - $TRAVIS_BUILD_DIR/miniconda3

# before_cache:
#   - rm -fr $TRAVIS_BUILD_DIR/miniconda3/envs

before_install:
  - uname -a
  - echo $TRAVIS_OS_NAME
  - pwd
  - if [[ ! -d $PWD/miniconda3 ]]; then
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
      bash miniconda.sh -b -p $PWD/miniconda3;
    fi
  - export PATH=$PWD/miniconda3/bin:$PATH;
  - which conda
  - conda install -y pytest h5py numba
  - which python
  - pip install pybind11
  - python -m pybind11 --include

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make tests
  - ./tests
  - cd ../python
  - pwd
  - python setup.py install
  - py.test

after_script:
  - pip uninstall treelas
