language: cpp
dist: xenial

git:
  submodules: false

branches:
  only:
    - master

# https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
#addons:
  # apt:
  #   sources:
  #     - ubuntu-toolchain-r-test
  #   packages:
  #     - g++-7
  ## don't need a specific compiler for macos
  # homebrew:
  #   packages:
  #     - gcc    ## https://formulae.brew.sh/formula/gcc

matrix:
  include:
    - os: linux
      # env: CXX_COMPILER=g++-7 C_COMPILER=gcc-7
    - os: osx
      # env: CXX_COMPILER=clang++ C_COMPILER=clang

cache:
  directories:
    - "$TRAVIS_BUILD_DIR/miniconda3"

before_cache:
  - pip uninstall -y treelas
  - rm -fr $TRAVIS_BUILD_DIR/miniconda3/envs
  - rm -fr $TRAVIS_BUILD_DIR/miniconda3/lib/python*/site-packages/treelas*

before_install:
  - git describe --tags

install:
  - uname -a && echo $TRAVIS_OS_NAME && pwd
  - export CC=${C_COMPILER:-cc} && echo $CC && $CC --version
  - export CXX=${CXX_COMPILER:-c++} && echo $CXX && $CXX --version
  - if [[ ! -d $PWD/miniconda3/bin ]]; then
      url="https://repo.continuum.io/miniconda/Miniconda3-latest";
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget $url-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget $url-MacOSX-x86_64.sh -O miniconda.sh;
    fi; rm -fr miniconda3; bash miniconda.sh -b -p $PWD/miniconda3; fi
  - export PATH=$PWD/miniconda3/bin:$PATH;
  - conda install -y pytest networkx h5py numba cmake
  - which python
  - which conda
  - pip install pybind11
  - python -m pybind11 --include
  - python -c 'from sys import byteorder as b; print("byte-order:", b)'
  - echo | ${CC} -dM -E -x c -

script:
  - mkdir -p build && cd build
  - CXX=$CXX CC=$CC cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make && ./tests
  - cd ../python && pwd && rm -fr build
  - CC=$CXX python setup.py install
  - py.test --color=yes test

notifications:
  email:
    on_failure: change
    on_success: change
