language: cpp
dist: bionic

git:
  submodules: false

sudo: false

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master

env:
  global:
    - curl="https://repo.continuum.io/miniconda/Miniconda3-latest"
    - CONDA_BASE="$TRAVIS_BUILD_DIR/miniconda3"

matrix:
  include:
    - &python
      language: python
      os: linux
      python: "3.7"
      install:
        - pip install --only-binary all -r python/requirements.txt -r python/test/requirements.txt
        - git submodule update --init deps/graphidx
        - (cd deps/graphidx && git submodule update --init deps/pybind11)
        - cd python && CC=c++ python setup.py install
      script: pytest test

    - <<: *python
      os: osx
 
    - language: julia
      os: linux  # don't need it specifically for osx
      julia: 1.2
      before_install:
        - git submodule update --init deps/graphidx
        - julia --color=yes -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(path="deps/graphidx/julia"))'
        - julia --color=yes -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(path="julia"))'
        - julia --color=yes -e 'import Pkg; Pkg.instantiate()'
      install:
        - julia --color=yes -e 'import Pkg; Pkg.build("TreeLas")'
        - julia --color=yes --project=docs/ -e 'import Pkg; Pkg.add("Documenter")'
      script:
        - julia --color=yes -e 'import Pkg; Pkg.test("TreeLas")'
        - julia --color=yes --project=docs/ docs/make.jl

    - language: rust
      os: linux
      rust: stable
      install:
        - git submodule update --init deps/graphidx
        - cargo --version
      script: cargo test

    - &cmake
      language: cpp
      os: linux
      env: cmake_opts="-DASAN=ON"
      install: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug $cmake_opts
      script: make -j$(nproc) && ./doctests -s

    - <<: *cmake
      os: osx
      env: cmake_opts="-DASAN=OFF"
