language: cpp

git:
  submodules: false

matrix:
  include:
    - env: CXX_COMPILER=g++-7 C_COMPILER=gcc-7
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    # - env: CXX=clang++ CC=clang
    #   os: osx

# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - $TRAVIS_BUILD_DIR/miniconda3

before_cache:
  - rm -fr $TRAVIS_BUILD_DIR/miniconda3/envs

branches:
  only:
    - master

install:
  - uname -a
  - export CXX=${CXX_COMPILER:-c++}
  - export CC=${C_COMPILER:-cc}
  - echo $CXX
  - $CXX --version
  - echo $TRAVIS_OS_NAME
  - pwd
  - if [[ ! -d $PWD/miniconda3/bin ]]; then
      url="https://repo.continuum.io/miniconda/Miniconda3-latest";
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget $url-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         wget $url-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
      rm -fr miniconda3;
      bash miniconda.sh -b -p $PWD/miniconda3;
    fi
  - export PATH=$PWD/miniconda3/bin:$PATH;
  - which conda
  - conda install -y pytest h5py numba
  - which python
  - pip install pybind11
  - python -m pybind11 --include

script:
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC
  - make tests && ./tests
  - cd ../python && pwd
  - python setup.py install
  - py.test

after_script:
  - pip uninstall -y treelas


notifications:
  email:
    on_failure: change
