shallow_clone: true

platform:
  - x64
# - x86

configuration:
  - Release
# - Debug

image:
  - Visual Studio 2015
# - Visual Studio 2017

environment:
  matrix:
    - MINICONDA: C:\Miniconda36-x64

init:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda install -y cmake h5py pytest

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - "cmake --build . --target tests --config %CONFIGURATION%"

test_script:
  - "%CONFIGURATION%/tests.exe"
