shallow_clone: true

platform:
  - x64
# - x86

configuration:
  - Release
# - Debug

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - MINICONDA: C:\Miniconda36-x64

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;$env:PATH"
