from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()
WIKI = "https://upload.wikimedia.org/wikipedia/commons"


rule download_all:
    input:
        'phantom.svg'


rule download_phantom:
    output:
        'phantom.svg'
    input:
        HTTP.remote(WIKI + "/c/c7/SheppLogan_Phantom.svg", keep_local=False)
    run:
        from decss import remove_css

        remove_css(input[0], output[0])


rule render_svg:
    input:  '{name}.svg'
    output: '{name}_w{width,\d+}.h5'
    run:
        from render_svg import gm_render
        import h5py
        import numpy as np

        seed = 2020
        std = 0.25
        np.random.seed(seed)
        y = gm_render(input[0], width=int(wildcards.width))
        y += np.random.normal(scale=std, size=y.shape)
        with h5py.File(output[0], 'w') as io:
            io.create_dataset('y', data=y)
            io.create_dataset("lam", data=[0.1])
