package:
  name: treelas
  version: v0.5

source:
  # git_rev: v0.4
  # git_url: https://github.com/eqt/treelas
  git_url: ../../..

requirements:
  build:
    - python
    - setuptools
    - pybind11
    - cmake
    - {{ compiler('cxx') }}
  run:
    - python
    - h5py
    - numba
test:
  imports:
    - treelas._treelas

about:
  home: https://github.com/eqt/treelas
  license: MIT
  license_file: LICENSE.md
