package:
  name: treelas
  version: v0.5

source:
  # git_rev: v0.4
  # git_url: https://github.com/eqt/treelas
  git_url: ../../..

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pybind11 >=2.2
  # run:
  #   - h5py
  #   - numba
test:
  imports:
    - treelas._treelas

about:
  home: https://github.com/eqt/treelas
  license: MIT
  license_file: LICENSE.md
