package:
  name: treelas
  version: v0.6

source:
  # git_rev: v0.6
  # git_url: https://github.com/eqt/treelas
  git_url: ../../..

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - vs2015_win-64 # [win]
  host:
    - vs2015_runtime # [win]
    - python
    - setuptools
    - pybind11 >=2.2
  # run:
  #   - h5py
  #   - numba
test:
  imports:
    - treelas._treelas

about:
  home: https://github.com/eqt/treelas
  license: MIT
  license_file: LICENSE.md
