package:
  name: treelas
  version: "0.5"

source:
  # git_rev: v0.4
  git_url: https://github.com/eqt/treelas
  # path: ../../..

requirements:
  build:
    - python
    - setuptools
    - pybind11     # from conda-forge
    - cmake
    - {{ compiler('cxx') }}
  run:
    - python
    - py-boost
    - libgcc-ng    # [linux]
    - libstdcxx-ng # [linux]
    - h5py
    - numba
test:
  imports:
    - treelas.tree

about:
  home: https://github.com/eqt/treelas
  license: MIT
  # license_file: LICENSE
