include: "../Snakefile"


rule generate_all:
    input: "randnorm_n1e7_f1e-7.treelas",
           "randmix_n1e7_f1e-7.treelas"


rule random_tree:
    output: "rand{dist,norm|exp|mix}_n{n}_f{f}_{seed,\\d+}.tree"
    run:
        from densetree import generate

        t = generate(int(float(wildcards.n)),
                     seed=int(float(wildcards.seed)),
                     dist=wildcards.dist,
                     factor=float(wildcards.f))
        t.save_h5(output[0])


rule binary_tree:
    output: "binary_n{n}{ignore,_.+}.tree"
    run:
        import h5py
        import numpy as np

        n = int(float(wildcards.n))
        parent = np.arange(-1, n-1) // 2
        parent[0] = 0
        with h5py.File(output[0], 'w') as io:
            io.create_dataset('parent', data=parent, compression=3)
