[package]
name = "treelas"
version = "0.1.0"
authors = ["Elias Kuthe <elias.kuthe@tu-dortmund.de>"]
edition = "2018"

[dependencies]
graphidx = { path = "../deps/graphidx/rust" }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
