from os import path

if path.exists("./config.yml"):
    configfile: "./config.yml"
elif path.exists("../config.yml"):
    configfile: "../config.yml"

CMAKE_BUILD = config["cmake_dir"]
LAMS = config["lam"]


subworkflow dimacs:
    workdir: "dimacs10"
    configfile: "./config.yml"


rule bench_dimacs:
    input:
        dimacs(expand("europe_{s}_lam{l}_rep{i}.tree_opt",
                      s=[1,2], l=LAMS, i=[1,2]))


rule run_treelas:
    input: "{name}.treelas"
    output: "{name}_lam{lam,[^_]+}{ignore}.tree_solve"
    shell: """
    {CMAKE_BUILD}/tree_solve -l {wildcards.lam} {input} | tee {output}
    """


rule run_treelas_no_output:
    input: "{name}.treelas"
    output: "{name}_lam{lam,[^_]+}{ignore}.tree_opt"
    shell: """
    {CMAKE_BUILD}/tree_solve -O -l {wildcards.lam} {input} | tee {output}
    """


rule run_treeapx:
    input: "{name}.treelas"
    output: "{name}.tree_apx"
    shell: "{CMAKE_BUILD}/tree_apx {input} | tee {output}"


rule spanning_tree:
    input: "{name}.h5"
    output: "{name}_{seed,\\d+}.tree"
    shell: """
    cp {input} {output} && {CMAKE_BUILD}/traverse -s {wildcards.seed} {output}
    """


rule noisy_input:
    input: "{name}.tree"
    output: "{name}.treelas"
    run:
        import numpy as np
        import h5py
        from shutil import copyfile

        np.random.seed(2020)
        copyfile(input[0], output[0])
        with h5py.File(output[0], "r+") as io:
            n = len(io["parent"])
            io.create_dataset("y", data=np.random.randn(n))
            io.create_dataset("lam", data=[0.1])
