// automatically generated by `julia/test/demo3x7.jl`
#pragma once

static const double demo_3x7_y[7][3] = {
  {0.62, 0.62, 0.9},
  {0.73, 1.73, 0.32},
  {0.71, 0.95, -0.48},
  {1.5, 1.46, 0.95},
  {1.17, 1.6, 1.08},
  {0.43, 1.16, 0.02},
  {1.08, 0.38, 0.4}
};
