// automatically generated by `julia/test/demo3x7.jl`
#pragma once

static const double demo_3x7_y[3][7] = {
  {0.62, 0.73, 0.71, 1.5, 1.17, 0.43, 1.08},
  {0.62, 1.73, 0.95, 1.46, 1.6, 1.16, 0.38},
  {0.9, 0.32, -0.48, 0.95, 1.08, 0.02, 0.4}
};
