#!/usr/bin/env python
"""
Parse CMakeLists.txt and update the source file list in setup.py.
"""
import re
from os import path


__dir__ = path.dirname(path.realpath(__file__))
cmake_txt = path.join(__dir__, '..', 'CMakeLists.txt')
setuppy   = path.join(__dir__, '..', 'python', 'setup.py')

with open(setuppy) as io:
    setup = io.read()
with open(cmake_txt) as io:
    cmake = io.read()

[mod] = re.findall(r'pybind11_add_module\(_treelas(.+?)\)', cmake, flags=re.DOTALL)

objs = {n : p.strip() for n, p in
        re.findall(r'add_object\((.+?) (.+?)\)', cmake, flags=re.DOTALL)}
objs['condat_tv'] = 'extern/condat/condat_tv_v2.cpp'
objs['tf_dp'] = 'extern/glmgen/tf_dp.cpp'

mods = re.sub(r'\$<TARGET_OBJECTS:(.+?)>', lambda n: objs[n.group(1)], mod)
source = ['"../' + s.strip() + '"' for s in mods.strip().split('\n')]
new_source = "sources = [\n    " + ",\n    ".join(source) + "\n]"
new_source = new_source.replace('../python/', '')
new_setup = re.sub(r'sources = \[(.+?)\]', new_source, setup, flags=re.DOTALL)

with open(setuppy, 'w') as io:
    io.write(new_setup)
