import h5py
from six.moves.urllib.request import urlretrieve


snap_url = "https://snap.stanford.edu/data"


rule all:
    input: "com-youtube.h5", "roadnet-ca.h5"


rule to_hdf5:
    input: "{name}.txt.gz"
    output: "{name}.h5"
    run:
        from pandas import read_csv
        df = read_csv(input[0], sep='\t', header=None, comment='#')
        with h5py.File(output[0], 'w') as io:
            g = io
            g.create_dataset("head", data=df[0].values, compression=3)
            g.create_dataset("tail", data=df[1].values, compression=3)


rule download_youtube:
    output: "com-youtube.txt.gz"
    run:
        urlretrieve(snap_url + "/bigdata/communities/com-youtube.ungraph.txt.gz",
                    filename=output[0])


rule download_road_ca:
    output: "roadnet-ca.txt.gz"
    run:
        urlretrieve(snap_url + "/roadNet-CA.txt.gz", filename=output[0])
