# https://www.cc.gatech.edu/dimacs10/archive/streets.shtml
from six.moves.urllib.request import urlretrieve
include: "../Snakefile"


URL = "https://www.cc.gatech.edu/dimacs10/archive/data/streets"
NAMES = ["asia", "belgium", "europe"]


rule download_all:
    input: expand("{name}.h5", name=NAMES)


rule download:
    output: "{name}.bz2"
    params: name="{name}"
    run:
        urlretrieve(f"{URL}/{params.name}.osm.graph.bz2", filename=output[0])


rule _python_to_hdf5:
    input: "{name}.bz2"
    output: "{name}.py.h5"
    run:
        from convert import convert

        convert(input[0], output[0])


rule julia_bzcat_to_hdf5:
    input: "{name}.bz2"
    output: "{name}.proc.h5"
    shell: "bzcat {input} | julia convert.jl - {output}"


rule julia_to_hdf5:
    input: "{name}.bz2"
    output: "{name}.jlh5"
    shell: "julia convert.jl {input} {output}"


rule convert_to_hdf5:
    input: "{name}.bz2", cmake("graph2h5")
    output: "{name}.h5"
    shell: "./{input[1]} {input[0]} {output}"


rule make_convert:
    input: "convert.cpp"
    output: "convert"
    shell: "make {output}"
